name: Skyrim Inventory Management Frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v7
        with:
          node-version: "26.5.0"
      - name: Enable Corepack
        run: corepack enable
      - name: Install Node Modules
        run: yarn
      - name: Compile Production Build
        run: yarn build
      - name: Format Code
        run: yarn format
      - name: Configure Playwright
        run: yarn playwright install
      - name: Build Storybook
        run: yarn build-storybook
      - name: Run tests
        run: yarn test
      - name: Verify test coverage
        run: yarn coverage
